[terminal.shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-s", "main"]

[font]
size = 12.0

[font.bold]
family = "Menlo"
style = "Bold"

[font.italic]
family = "Menlo"
style = "Italic"

[font.normal]
family = "Menlo"
style = "Regular"
